baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'Rene Jensen'

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions]
footnote = true

[build]
writeStats = true

[taxonomies]
tag = "tags"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 2
  [[menu.main]]
    name = "Guide to CPH"
    url = "/guidetocph/"
    weight = 3
  [[menu.main]]
    name = "Resources"
    url = "/resources/"
    weight = 4
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5
